#!/bin/bash

/github/home/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-g++ \
  "$@" \
  | sed 's|: xtensa-esp32-elf|: le32-unknown-nacl|g' \
  | sed 's|=xtensa-esp32-elf|=le32-unknown-nacl|g'
